services:
  bootcamp.api:
    image: bootcamp.api
    build:
      context: .
      dockerfile: Bootcamp.Api/Dockerfile
    env_file:
      - Bootcamp.Api/.env
    depends_on:
        postgres:
          condition: service_healthy
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    env_file:
      - Bootcamp.Api/.env
    ports:
      - "6666:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d Bootcamp" ]
      interval: 1s
      timeout: 10s
      retries: 5
      
  grafana:
    image: grafana/grafana:latest
    ports:
    - "7777:3000"
    env_file:
      - Bootcamp.Api/.env
    volumes:
      - grafana_data:/var/lib/grafana
      
volumes:
  postgres_data:
  grafana_data: