POST http://localhost:8080/generate-text
Content-Type: application/json
Accept: application/json

{
  "prompt": "Представь ты помощник студента, помоги му с вопросом. Вопрос: Как добраться в аудиторию из столовой? (ты знаешь карту или сам её придумай)",
  "temperature": 0.9
}

###

POST http://localhost:8080/register
Content-Type: application/json
Accept: application/json

{
  "firstName": "Yaroslav",
  "lastName": "Rofl",
  "email": "rofl@rofl.rofl",
  "password": "abCD123!"
}

> {%
    client.test("Register successful", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.log("Token: " + response.body.token);
        client.global.set("auth_token", response.body.token);
    });
%}

###

POST http://localhost:8080/login
Content-Type: application/json
Accept: application/json

{
  "email": "rofl@rofl.rofl",
  "password": "abCD123!"
}

> {%
    client.test("Login successful", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.global.set("auth_token", response.body.token);
    });
%}

###

GET http://localhost:8080/users/me
Authorization: Bearer {{auth_token}}

> {%
    client.test("Profile fetched", function() {
        client.assert(response.status === 200, "Failed to fetch profile");
        client.log("User: " + JSON.stringify(response.body));
    });
%}

###

POST http://localhost:8080/jobs/create
Content-Type: application/json

{
  "jobName": "Senior Backend Developer",
  "description": "Разработка высоконагруженных микросервисов на C#",
  "company": "Tech Innovations Inc.",
  "requirements": [
    "Опыт работы с .NET Core 5+",
    "Знание Docker и Kubernetes",
    "Опыт работы с базами данных PostgreSQL",
    "Понимание принципов REST/gRPC"
  ],
  "jobType": "Intern",
  "salary": 250000.50,
  "salaryDescription": "{0} $ в час"
}

> {%
    client.test("Job create successful", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.global.set("job_id", response.body);
    });
%}

###

GET http://localhost:8080/jobs/{{job_id}}

###

POST http://localhost:8080/jobs/{{job_id}}/active

###

POST http://localhost:8080/jobs/{{job_id}}/disable