POST http://localhost:8080/generate-text
Content-Type: application/json
Accept: application/json

{
  "prompt": "Представь ты помощник студента, помоги му с вопросом. Вопрос: Как добраться из кампуса из столовой? (ты знаешь карту или сам её придумай)",
  "temperature": 0.9
}
###
